"""initial migration

Revision ID: 86724c04af49
Revises: 
Create Date: 2019-03-22 12:06:58.599438

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86724c04af49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('home_client',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('home_feature',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('client', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_priority', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),



    sa.Column('request_status', sqlalchemy_utils.types.choice.ChoiceType(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Ongoing'), (4, 'Rescheduled'), (5, 'Completed')], impl=sa.Integer()), nullable=True),
    sa.Column('product_area', sqlalchemy_utils.types.choice.ChoiceType(choices=[(0, 'Policies'), (1, 'Billing'), (2, 'Claims'), (3, 'Reports')], impl=sa.Integer()), nullable=True),
    sa.Column('requested_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['home_client.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client', 'client_priority', name='unique_client_feature_priority'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_feature')
    op.drop_table('home_client')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
