"""empty message

Revision ID: d6e07b6c333d
Revises: 86724c04af49
Create Date: 2019-03-23 18:00:25.035839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e07b6c333d'
down_revision = '86724c04af49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_user', ['id'])
    op.create_unique_constraint(None, 'home_client', ['id'])
    op.drop_constraint('unique_client_feature_priority', 'home_feature', type_='unique')
    op.create_unique_constraint(None, 'home_feature', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_feature', type_='unique')
    op.create_unique_constraint('unique_client_feature_priority', 'home_feature', ['client', 'client_priority'])
    op.drop_constraint(None, 'home_client', type_='unique')
    op.drop_constraint(None, 'auth_user', type_='unique')
    # ### end Alembic commands ###
